<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_user_password-297</name>
   <tag></tag>
   <elementGuidId>1e98cd39-05d7-4e61-abbe-f69698cbc30e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c8c1c2c-1c65-4d5f-b264-90e66e5c4072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid</value>
      <webElementGuid>53b7302e-fb62-4da8-b8f9-ae3fc3c7a1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2d05d58d-0bd3-4d64-afeb-e328b1d5e3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>aa352b18-b9dd-4c49-be75-b70b32a04308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>e143d6d8-82dc-492b-b4ec-fa7a1f311f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_password</value>
      <webElementGuid>7121fa96-b789-481f-987b-f22965a94439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password-297&quot;)</value>
      <webElementGuid>10c1bb53-038e-4dcb-a220-b80b84c5ac3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password-297']</value>
      <webElementGuid>8e75991c-c238-42d8-966a-d2aa861dda4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_password']/div[2]/input</value>
      <webElementGuid>85eb28a7-d0eb-43f6-ab26-e27f308b8b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>6416e35c-5121-40ad-a9c6-d55cd1ee8b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_password-297' and @id = 'user_password-297']</value>
      <webElementGuid>e3e6e573-1d52-4be6-add2-8b9688c4a9bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
