<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_confirm_user_password-297</name>
   <tag></tag>
   <elementGuidId>78f19118-7a39-4015-b726-7a2e01433ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm_user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c36f7c58-f062-429f-a008-3bd758272dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid um-validate-not-matched</value>
      <webElementGuid>0b550b10-2088-4d5f-9a15-b63e6b77c963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5d18d666-5163-47fe-abd2-61e62fa3d978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>d48fda04-cfbf-4d99-9322-6bbcd2a08320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>62745986-f44f-4607-86bf-99275264163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>21539bca-a509-452c-92c2-d92ca39bad58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>confirm_user_password</value>
      <webElementGuid>069119fa-0072-41e3-8996-5c47fcf903d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_user_password-297&quot;)</value>
      <webElementGuid>4148b504-e85c-44a5-9be7-8db720a2b8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_user_password-297']</value>
      <webElementGuid>c2661f76-87b2-4104-8d53-f8470ce635e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_confirm_user_password']/div[2]/input</value>
      <webElementGuid>f066489d-5dc2-445a-8d3b-05d99e9a685c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>bd96fee0-374b-41a3-a02e-a2053ebd3770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_user_password-297' and @id = 'confirm_user_password-297' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>94c1c631-149b-47dd-869f-a41d742e0ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
